[package]
name = "coldwar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
quick-xml = "0.31.0"
reqwest = "0.12.4"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
walkdir = "2.5.0"
